#!/usr/bin/env bash
#
# device_audit.sh — T00 Meebook e-ink device audit (read-only)
#
# Purpose:
#   Collect the confirmed build/display/e-ink characteristics of the connected
#   Meebook device over ADB, so that T01 can pick correct build constraints
#   (minSdk, ABI, screen density) and the e-ink strategy.
#
# Safety contract (see AGENT_EXECUTION_PLAN.md, card T00):
#   - READ-ONLY. No root, no `settings put`, no `pm install/uninstall`,
#     no reboot, no decompilation, no system setting changes.
#   - Every command here is a getprop / list / dumpsys read or a `logcat -d` dump.
#   - Output is redacted: serial numbers, IMEI/MEID, Google/other accounts,
#     Wi-Fi/Bluetooth MAC and Android IDs are scrubbed before being written.
#   - Idempotent: safe to run repeatedly. Re-running overwrites the timestamped
#     run directory content deterministically; nothing is appended blindly.
#
# Usage:
#   ./scripts/device_audit.sh                # audit the single connected device
#   ADB=/path/to/adb ./scripts/device_audit.sh
#   OUT_DIR=artifacts/device-audit ./scripts/device_audit.sh
#
# Exit codes:
#   0  audit completed and written
#   2  adb not found
#   3  no device / unauthorized device
set -uo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
ADB="${ADB:-adb}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${OUT_DIR:-$REPO_ROOT/artifacts/device-audit}"
SUMMARY="$OUT_DIR/summary.txt"

mkdir -p "$OUT_DIR"

log()  { printf '[audit] %s\n' "$*" >&2; }
warn() { printf '[audit][WARN] %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# Redaction. Applied to every captured line before it is written to disk.
# Removes: serial numbers, IMEI/MEID, MAC addresses, Android IDs, account
# names/emails, and known secret-looking properties. Fail-closed: if a value
# is a known-sensitive property key we drop the whole line.
# ---------------------------------------------------------------------------
redact() {
  sed -E \
    -e 's/([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}/[REDACTED_MAC]/g' \
    -e 's/\b[0-9]{15,17}\b/[REDACTED_NUM_ID]/g' \
    -e 's/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/[REDACTED_EMAIL]/g' \
    -e 's/(ro\.serialno|ro\.boot\.serialno|ril\.serialnumber|persist\.sys\.serialno)[]:= ]+.*/\1=[REDACTED_SERIAL]/Ig' \
    -e 's/(ro\.boot\.wifimacaddr|ro\.boot\.btmacaddr)[]:= ]+.*/\1=[REDACTED_MAC]/Ig' \
    -e 's/(android_id|gsf_id|advertising_id)[]:=" ]+[0-9A-Fa-f]+/\1=[REDACTED_ID]/Ig'
}

# Run an adb shell command, redact, and tee to a section file + summary header.
# $1 = section label, $2 = output filename (basename), rest = adb shell args
capture() {
  local label="$1"; shift
  local file="$1"; shift
  local dest="$OUT_DIR/$file"
  log "collect: $label"
  {
    printf '### %s\n' "$label"
    printf '# command: adb shell %s\n' "$*"
  } > "$dest"
  if "$ADB" shell "$@" 2>>"$dest" | redact >> "$dest"; then
    :
  else
    warn "command failed: $label"
  fi
}

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
if ! command -v "$ADB" >/dev/null 2>&1; then
  warn "adb not found (looked for: $ADB)."
  warn "Install Android platform-tools first, e.g.:"
  warn "  macOS:  brew install --cask android-platform-tools"
  warn "  Or download: https://developer.android.com/tools/releases/platform-tools"
  exit 2
fi

log "adb: $("$ADB" version | head -1)"

# Count authorized devices (state == 'device'). 'unauthorized'/'offline' don't count.
DEVICE_LINE_COUNT="$("$ADB" devices | awk 'NR>1 && $2=="device"{c++} END{print c+0}')"
if [ "$DEVICE_LINE_COUNT" -eq 0 ]; then
  warn "No authorized device connected."
  warn "Checklist:"
  warn "  1. Enable Developer options (Settings > About > tap Build number 7x)."
  warn "  2. Enable USB debugging in Developer options."
  warn "  3. Connect USB cable and accept the 'Allow USB debugging?' prompt on device."
  warn "  4. Re-run: adb devices  (device must show state 'device', not 'unauthorized')."
  "$ADB" devices >&2 || true
  exit 3
fi
if [ "$DEVICE_LINE_COUNT" -gt 1 ]; then
  warn "Multiple devices connected; set ANDROID_SERIAL to target one. Continuing with default."
fi

# ---------------------------------------------------------------------------
# Collection (all read-only)
# ---------------------------------------------------------------------------
: > "$SUMMARY"
{
  printf '# Meebook device audit — raw summary\n'
  printf '# generated by scripts/device_audit.sh (read-only, redacted)\n'
  printf '# adb: %s\n\n' "$("$ADB" version | head -1)"
} >> "$SUMMARY"

# --- 1. Identity & build ---------------------------------------------------
log "== identity & build =="
{
  printf '## identity & build\n'
  for prop in \
    ro.product.manufacturer ro.product.brand ro.product.model ro.product.device \
    ro.product.name ro.build.product ro.board.platform \
    ro.build.version.release ro.build.version.sdk ro.build.version.security_patch \
    ro.build.fingerprint ro.build.display.id; do
    val="$("$ADB" shell getprop "$prop" 2>/dev/null | tr -d '\r' | redact)"
    printf '%-38s = %s\n' "$prop" "$val"
  done
} >> "$SUMMARY"

# --- 2. ABI / bitness ------------------------------------------------------
log "== ABI / bitness =="
{
  printf '\n## ABI / bitness\n'
  for prop in \
    ro.product.cpu.abi ro.product.cpu.abilist \
    ro.product.cpu.abilist32 ro.product.cpu.abilist64 \
    ro.zygote; do
    val="$("$ADB" shell getprop "$prop" 2>/dev/null | tr -d '\r' | redact)"
    printf '%-38s = %s\n' "$prop" "$val"
  done
  # ro.zygote == zygote64_32 or zygote64 => 64-bit userspace present.
  printf '# interpretation: ro.zygote=zygote32 => 32-bit only; zygote64* => 64-bit userspace.\n'
} >> "$SUMMARY"

# --- 3. Display: size & density -------------------------------------------
log "== display =="
{
  printf '\n## display\n'
  printf 'wm size    : %s\n'    "$("$ADB" shell wm size 2>/dev/null | tr -d '\r' | redact)"
  printf 'wm density : %s\n'    "$("$ADB" shell wm density 2>/dev/null | tr -d '\r' | redact)"
} >> "$SUMMARY"
capture "display: dumpsys display (physical)" "display_dumpsys.txt" dumpsys display

# --- 4. e-ink / vendor package & service discovery -------------------------
log "== e-ink discovery =="
capture "all installed packages" "packages_all.txt" pm list packages
{
  printf '\n## e-ink / vendor candidates (filtered from packages_all.txt & getprop)\n'
  printf '# packages matching eink|epd|boyue|likebook|meebook|onyx|rockchip:\n'
  "$ADB" shell pm list packages 2>/dev/null | tr -d '\r' \
    | grep -iE 'eink|epd|boyue|likebook|meebook|onyx|rk|rockchip' | redact \
    || printf '  (none matched)\n'
  printf '# system properties mentioning eink/epd:\n'
  "$ADB" shell getprop 2>/dev/null | tr -d '\r' \
    | grep -iE 'eink|epd|boyue|likebook|meebook' | redact \
    || printf '  (none matched)\n'
} >> "$SUMMARY"

# system services (names only — no account/secret dumps)
capture "system service names" "services.txt" service list

# --- 5. Full getprop snapshot (redacted) -----------------------------------
capture "getprop (full, redacted)" "getprop_full.txt" getprop

# --- 6. logcat: e-ink refresh-mode hints -----------------------------------
# Non-blocking snapshot of the current buffer. To capture Normal/Regal/A2
# transitions, clear the buffer, toggle the mode manually on-device, then
# re-run — the diff will contain the vendor broadcast/command, if any.
log "== logcat snapshot (buffer dump) =="
{
  printf '### logcat -d filtered for e-ink keywords\n'
  printf '# To capture mode switches: run `adb logcat -c`, toggle Normal/Regal/A2\n'
  printf '# manually on the device, then re-run this script.\n'
} > "$OUT_DIR/logcat_eink.txt"
"$ADB" logcat -d 2>/dev/null | tr -d '\r' \
  | grep -iE 'eink|epd|refresh|regal|a2|gc16|boyue' | redact \
  >> "$OUT_DIR/logcat_eink.txt" || warn "logcat dump failed"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
log "audit complete. Redacted output in: $OUT_DIR"
log "review $SUMMARY, then transcribe confirmed values into DEVICE_AUDIT.md"
echo "$SUMMARY"
